server:
  port: 8800

eureka:
  client:
    register-with-eureka: true #유레카 클라이언트 활성화
    fetch-registry: true #DefaultZone의 유레카 서버에서 클라리언트 정보를 가져옴(캐싱해놓는다)
  service-url:
    default-zone: http://localhost:8761/eureka # 유레카 클라이언트로 등록

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: spring-service
          #uri: http://localhost:9002
          uri: lb://SPRING-SERVICE
          predicates:
            - Path=/spring-service/**
        - id: yanolja-service
          #uri: http://localhost:8080
          uri: lb://YANOLJA-SERVICE
          predicates:
            - Path=/yanolja/**
          filters:
            - RewritePath=/yanolja/(?<path>.*),/$\{path}







