server:
  port: 9200 #8800

spring:
  application:
    name: yanolja-service
    #  cloud:
    #    gateway:
    #      routes:
    #        - id: yanolja-service
    #          uri: http://localhost:8080
    #          predicates:
    #            - Path=/yanolja/**
    #          filters:
    #            - RewritePath=/yanolja/(?<path>.*),/$\{path}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    default-zone: http://localhost:8761/eureka




